//var shuffleSequence = seq("home","intro","fam","sexp", sepWith("sep", rshuffle("iller","e")));
var shuffleSequence = seq("home","intro","fam", sepWith("sep", "practice"),"sexp",sepWith("sep", rshuffle("iller","e")));
//var shuffleSequence = seq("home","intro","fam", sepWith("sep", "practice"),"sexp",sepWith("sep","iller","e"));
//var shuffleSequence = seq("home","intro","fam","iller", "e");
//var shuffleSequence = seq("e","iller");
var completionMessage = "[Grazie per aver completato questo esperimento!I tuoi risultati sono stati corretamente salvati. Questo esperimento ha lo scopo di studiare come si risponde in italiano alle domande negative. Per qualunque domanda puoi scrivere a giuliano.bocci@unige.ch ]";
var practiceItemTypes = ["practice"];
var practiceMessage = "Schermata di prova";

var defaults = [
    "Separator", {
        transfer: 1000,
        normalMessage: "Caricamento della schermata in corso",
        errorMessage: "Errore. Caricamento della schermata in corso."
    },
    "DashedSentence", {
        mode: "self-paced reading"
    },
    "AcceptabilityJudgment", {
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        instructions: "Use number keys or click boxes to answer.",
        leftComment: "(Bad)", rightComment: "(Good)"
    },
    "Question", {
        hasCorrect: false
    },
    "Message", {
        hideProgressBar: true
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: false
    },
    "Formit", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: false
    }
];

var items = [

    // New in Ibex 0.3-beta-9. You can now add a '__SendResults__' controller in your shuffle
    // sequence to send results before the experiment has finished. This is NOT intended to allow
    // for incremental sending of results -- you should send results exactly once per experiment.
    // However, it does permit additional messages to be displayed to participants once the
    // experiment itself is over. If you are manually inserting a '__SendResults__' controller into
    // the shuffle sequence, you must set the 'manualSendResults' configuration variable to 'true', since
    // otherwise, results are automatically sent at the end of the experiment.
    //
    //["sr", "__SendResults__", { }],

    ["sep", "Separator", { }],

    // New in Ibex 0.3-beta19. You can now determine the point in the experiment at which the counter
    // for latin square designs will be updated. (Previously, this was always updated upon completion
    // of the experiment.) To do this, insert the special '__SetCounter__' controller at the desired
    // point in your running order. If given no options, the counter is incremented by one. If given
    // an 'inc' option, the counter is incremented by the specified amount. If given a 'set' option,
    // the counter is set to the given number. (E.g., { set: 100 }, { inc: -1 })
    //
    //["setcounter", "__SetCounter__", { }],

    // NOTE: You could also use the 'Message' controller for the experiment intro (this provides a simple
    // consent checkbox).

    ["home", "Formit", {
        html: { include: "home.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],
    ["intro", "Formit", {
        html: { include: "example_intro.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],
    ["fam", "Formit", {
        html: { include: "iniziofam.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],
    ["sexp", "Formit", {
        html: { include: "inizioexp.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],
    //
    // Three practice items for self-paced reading (one with a comprehension question).
    //

    //["practice", "DashedSentence", {s: "QUESTA E UNA PROVA :-) USA LA BARRA SPAZIATRICE"}],
    ["practice", "Question", {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F32.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo fratello &egrave; raffreddato.<br>Sapendo di fargli piacere, gli prepari una tazza di t&egrave; caldo.<br>Sai per&ograve; che il t&egrave; gli piace non troppo forte, quindi lasci la bustina in infusione per tre minuti esatti, e la togli.<br>Tuo fratello, che ti sente armeggiare in cucina gi&agrave; da parecchi minuti, ti chiede:<br><strong>-Hai tolto la bustina dalla tazza?<br></strong><span style=\"color:#696969;\"><em><br><br>In questa situazione, che cosa risponderesti?<br>Se non hai ben capito il contesto, prima di rispondere riascolta la spiegazione del contesto e la domanda cliccando su Play.<br></em></span></div>", as: ["S&igrave;", "No"]}],
    ["practice", "Question", {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F05.mp3' type='audio/mpeg'></source></audio> <br><br><br>Dopo una grande cena, c&#39;&egrave; una gran massa di piatti da lavare.<br>La lavastoviglie &egrave; quasi piena.<br>Non c&#39;&egrave; spazio per tutte le posate: decidi quindi di mettere dentro le forchette, e di lavare i coltelli e i cucchiai a mano. Il tuo coinquilino, nella gran confusione, non capisce bene e ti chiede:<br /><strong>-LE FORCHETTE hai messo nella lavastoviglie?<br></strong><br><br><span style=\"color:#696969;\"><em><br><br>In questa situazione, che cosa risponderesti?<br>Se non hai ben capito il contesto, prima di rispondere riascolta la spiegazione del contesto e la domanda cliccando su Play.<br></em></span></div>", as: ["S&igrave;", "No"]}],
    ["practice", "Question", {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F21.mp3' type='audio/mpeg'></source></audio> <br><br><br>A casa vostra c&#39;&egrave; un armadietto in cui tenete i medicinali, pi&ugrave; altri dispositivi medici come il termometro e i cerotti.<br>Dentro c&#39;&egrave; una certa confusione. Il tuo coinquilino apre l&#39;armadietto e non riesce a trovare il termometro, che &egrave; nascosto dalle scatole dei farmaci.<br>Ti chiede allora:<br /><strong>-Hai tolto il termometro dall&#39;armadietto?<br></strong><span style=\"color:#696969;\"><em><br><br>In questa situazione, che cosa risponderesti?<br> Se non hai ben capito il contesto, prima di rispondere riascolta la spiegazione del contesto e la domanda cliccando su Play.<br></em></span></div>", as: ["S&igrave;", "No"]}],

    //
    // Two "real" (i.e. non-filler) self-paced reading items with corresponding acceptability judgment items.
    // There are two conditions.
    //

    // The first question will be chosen if the first sentence from the previous two items is chosen;
    // the second question will be chosen if the second sentence from the previous pair of items is chosen.
    [["e",1], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g011_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Hai organizzato una festa per il tuo compleanno.<br> &nbsp;C&#39;&egrave; un problema: i tuoi amici Marta e Gianni non si sopportano proprio.<br> Parlandone col tuo coinquilino, decidi che non puoi invitarli entrambi.<br> Quando si tratta di spedire gli inviti, sei in dubbio fra i due.<br> Alla fine, decidi di non invitare Gianni.<br> Il giorno della festa il tuo coinquilino nota una ragazza di spalle che gli sembra essere Marta, allora ti domanda:<br /><strong>-GIANNI non hai invitato alla festa?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",1], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g013_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Hai organizzato una festa per il tuo compleanno.<br> Parlandone col tuo coinquilino, prepari la lista degli invitati e includi anche il tuo vecchio amico Gianni.<br> All&#39;ultimo momento, per&ograve;, ti ricordi di alcune sgradevolezze fatte da Gianni ad un&#39;altra festa in passato.<br> Decidi quindi di non invitarlo.<br> Il giorno della festa il tuo coinquilino entra nel salone e non vede Gianni da nessuna parte.<br> Allora ti domanda:<br /><strong>-Non hai invitato Gianni alla festa?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",1], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g011_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Hai organizzato una festa per il tuo compleanno.<br> &nbsp;C&#39;&egrave; un problema: i tuoi amici Marta e Gianni non si sopportano proprio.<br> Parlandone col tuo coinquilino, decidi che non puoi invitarli entrambi.<br> Quando si tratta di spedire gli inviti, sei in dubbio fra i due.<br> Alla fine, decidi di non invitare Marta.<br> Il giorno della festa il tuo coinquilino nota una ragazza di spalle che gli sembra essere Marta, allora ti domanda:<br /><strong>-GIANNI non hai invitato alla festa?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",1], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g013_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Hai organizzato una festa per il tuo compleanno.<br> Parlandone col tuo coinquilino, prepari la lista degli invitati e includi anche il tuo vecchio amico Gianni.<br> Il giorno della festa il tuo coinquilino entra nel salone e non vede Gianni da nessuna parte.<br> Allora ti domanda:<br /><strong>-Non hai invitato Gianni alla festa?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",2], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g021_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il tuo coinquilino Mario sta facendo delle domande di lavoro.<br> Una mattina, Mario, prima di andare all&#39;universit&agrave;, ti lascia a casa due buste da lettera, una rossa e una azzurra.<br> Ti chiede di spedire per posta la busta azzurra al Ministero, ma di non spedire la busta rossa: la consegner&agrave; a mano il giorno dopo.<br> Sbadatamente, andando alla posta nel pomeriggio spedisci la busta rossa invece di quella azzurra.<br> La sera, Mario, vedendo la busta azzurra ancora sul tavolo, ti chiede:<br /><strong>-LA BUSTA AZZURRA non hai spedito al Ministero?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",2], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g023_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il tuo coinquilino Mario sta facendo delle domande di lavoro.<br> Una mattina, Mario, prima di andare all&#39;universit&agrave;, ti lascia a casa una busta da lettera azzurra.<br> Ti chiede di spedirla per posta al Ministero.<br> Sbadatamente, andando alla posta nel pomeriggio dimentichi di farlo.<br> La sera, Mario, vedendo la busta azzurra ancora sul tavolo, ti chiede:<br /><strong>-Non hai spedito la busta azzurra al Ministero?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",2], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g021_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il tuo coinquilino Mario sta facendo delle domande di lavoro.<br> Una mattina, Mario, prima di andare all&#39;universit&agrave;, ti lascia a casa due buste da lettera, una rossa e una azzurra.<br> Ti chiede di spedire per posta la busta azzurra al Ministero, ma di non spedire la busta rossa: la consegner&agrave; a mano il giorno dopo.<br> Vai alla posta nel pomeriggio e spedisci la busta azzurra, come d&#39;accordo .<br> La sera, Mario, vedendo qualcosa di colore azzurro sul tavolo, ti chiede:<br /><strong>-LA BUSTA AZZURRA non hai spedito al Ministero?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",2], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g023_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il tuo coinquilino Mario sta facendo delle domande di lavoro.<br> Una mattina, Mario, prima di andare all&#39;universit&agrave;, ti lascia a casa una busta da lettera azzurra.<br> Ti chiede di spedirla per posta al Ministero.<br> Nel pomeriggio vai alla posta e la spedisci.<br> La sera per&ograve; Mario, vedendo qualcosa di colore azzurro sul tavolo, ti chiede:<br /><strong>-Non hai spedito la busta azzurra al Ministero?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",3], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g031_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Una anziana parente ti incarica di trattare con alcuni collezionisti russi la vendita della sua collezione di antiquariato, ma ti dice che se c&#39;&egrave; un pezzo che ti piace in modo particolare puoi non venderlo e tenerlo per te.<br> Non sai deciderti fra un orologio e un servizio da t&egrave;, e ne discuti con un tuo amico.<br> Dopo per&ograve; i collezionisti si offrono di comprare tutta la collezione in blocco, salvo l&#39;orologio.<br> Dato l&#39;ottimo prezzo, accetti.<br> A cose fatte il tuo amico ti domanda:<br /><strong>-L&#39;OROLOGIO non hai venduto ai russi?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",3], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g033_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Una anziana parente ti incarica di trattare con alcuni collezionisti russi la vendita della sua collezione di antiquariato, ma ti dice che se c&#39;&egrave; un pezzo che ti piace in modo particolare puoi non venderlo e tenerlo per te.<br> I collezionisti si offrono di comprare tutta la collezione in blocco, salvo l&#39;orologio.<br> Dato l&#39;ottimo prezzo, accetti.<br> A cose fatte un tuo amico, vedendo l&#39;orologio nel tuo salotto, ti domanda:<br /><strong>-Non hai venduto l&#39;orologio ai russi?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",3], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g031_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Una anziana parente ti incarica di trattare con alcuni collezionisti russi la vendita della sua collezione di antiquariato, ma ti dice che se c&#39;&egrave; un pezzo che ti piace in modo particolare puoi non venderlo e tenerlo per te.<br> Non sai deciderti fra un orologio e un servizio da t&egrave;, e ne discuti con un tuo amico.<br> Dopo per&ograve; i collezionisti si offrono di comprare tutta la collezione in blocco, salvo il servizio da t&egrave;.<br> Dato l&#39;ottimo prezzo, accetti.<br> A cose fatte il tuo amico ti domanda:<br /><strong>-L&#39;OROLOGIO non hai venduto ai russi?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",3], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g033_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Una anziana parente ti incarica di trattare con alcuni collezionisti russi la vendita della sua collezione di antiquariato, ma ti dice che se c&#39;&egrave; un pezzo che ti piace in modo particolare puoi non venderlo e tenerlo per te.<br> I collezionisti si offrono di comprare tutta la collezione in blocco, incluso un grande orologio.<br> Dato l&#39;ottimo prezzo, accetti.<br> A cose fatte un tuo amico, vedendo nel tuo salotto un orologio che assomiglia vagamente a quello di tua nonna, ti domanda:<br /><strong>-Non hai venduto l&#39;orologio ai russi?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",4], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g041_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori nella biblioteca universitaria.<br> Certe categorie di opere non vengono date in prestito agli studenti.<br> In particolare, non vanno in prestito gli atlanti geografici.<br> Un collega assunto da poco ha ancora le idee confuse in materia.<br> Quando ti vede dare in prestito un manuale di geografia a uno studente, vuole assicurarsi di aver capito bene e ti domanda:<br /><strong>-GLI ATLANTI non prestiamo agli studenti?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",4], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g043_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori nella biblioteca universitaria.<br> Certe categorie di opere non vengono date in prestito agli studenti.<br> In particolare, non vanno in prestito gli atlanti geografici.<br> Un collega assunto da poco non &egrave; al corrente del regolamento.<br> Quando ti vede rifiutare a uno studente il prestito di un atlante vuole assicurarsi di aver capito bene e ti domanda:<br /><strong>-Non prestiamo gli atlanti agli studenti?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",4], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g041_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori nella biblioteca universitaria.<br> Certe categorie di opere non vengono date in prestito agli studenti.<br> In particolare, non vanno in prestito i dizionari.<br> Un collega assunto da poco ha ancora le idee confuse in materia.<br> Quando ti vede dare in prestito un manuale di geografia a uno studente, vuole assicurarsi di aver capito bene e ti domanda:<br /><strong>-GLI ATLANTI non prestiamo agli studenti?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",4], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g043_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori nella biblioteca universitaria.<br> I volumi della biblioteca vengono tutti liberamente dati in prestito agli studenti, purch&eacute; non abbiano la rilegatura danneggiata: in quel caso il prestito del volume viene sospeso per permetterne la riparazione.<br> Un collega assunto da poco non &egrave; al corrente del regolamento.<br> Ti vede rifiutare a uno studente il prestito di un vecchio atlante con la copertina staccata, quindi ti domanda:<br /><strong>-Non prestiamo gli atlanti agli studenti?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",5], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g051_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il vostro gatto di casa &egrave; affetto da una misteriosa allergia.<br> Hai a lungo creduto che fosse allergico al salmone, ma studiando bene i suoi sintomi hai capito che &egrave; invece allergico al tonno.<br> Un tuo amico ti accompagna al supermercato e nota che ti soffermi a lungo a scegliere le scatolette di cibo per gatti, scartandone varie.<br> Allora ti domanda:<br /><strong>-IL TONNO non dai al gatto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",5], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g053_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il vostro gatto di casa &egrave; affetto da una misteriosa allergia.<br> Studiando bene i suoi sintomi hai capito che &egrave; allergico al tonno.<br> Un tuo amico, che non &egrave; al corrente del problema, ti accompagna al supermercato e si sorprende notando che ti soffermi a lungo a scegliere le scatolette di cibo per gatti, scartando quelle a base di tonno.<br> Allora ti domanda:<br /><strong>-Non dai il tonno al gatto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",5], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g051_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il vostro gatto di casa &egrave; affetto da una misteriosa allergia.<br> Hai a lungo creduto che fosse allergico al tonno, ma studiando bene i suoi sintomi hai capito che &egrave; invece allergico al salmone.<br> Un tuo amico ti accompagna al supermercato e nota che ti soffermi a lungo a scegliere le scatolette di cibo per gatti, scartandone varie.<br> Allora ti domanda:<br /><strong>-IL TONNO non dai al gatto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",5], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g053_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il vostro gatto di casa &egrave; affetto da una misteriosa allergia.<br> Alcune marche di cibo per gatti, per&ograve;, non sembrano dargli problemi.<br> Un tuo amico, che non &egrave; al corrente del problema, ti accompagna al supermercato e si sorprende notando che ti soffermi a lungo a scegliere le scatolette di cibo per gatti, scartandone anche alcune a base di tonno.<br> Allora ti domanda:<br /><strong>-Non dai il tonno al gatto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",6], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g061_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo zio Luciano ha gusti originali.<br> E&#39; un grande appassionato di scienza ed economia ma si vanta di non leggere romanzi.<br> Un tuo amico &egrave; invitato insieme a te alla festa di compleanno di zio Luciano.<br> Deve scegliere un regalo per tuo zio, ed essendo la prima volta non &egrave; sicuro di aver capito bene.<br> Allora ti domanda:<br /><strong>-I ROMANZI non regali a tuo zio?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",6], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g063_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo zio Luciano ha gusti originali: si vanta infatti di non leggere romanzi.<br> Un tuo amico &egrave; invitato insieme a te alla festa di compleanno di zio Luciano.<br> Ti chiede di accompagnarlo in centro per comprare un regalo a Luciano.<br> Pensava di regalargli un romanzo che gli piace molto.<br> Tu gli dici che non ti sembra molto appropriato.<br> Lui ti domanda allora:<br /><strong>-Non regali i romanzi a tuo zio?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",6], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g061_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo zio Luciano ha gusti originali.<br> E&#39; un grande appassionato di scienza ed economia ma si vanta di non leggere poesie.<br> Un tuo amico &egrave; invitato insieme a te alla festa di compleanno di zio Luciano.<br> Deve scegliere un regalo per tuo zio, ed essendo la prima volta non &egrave; sicuro di aver capito bene.<br> Allora ti domanda:<br /><strong>-I ROMANZI non regali a tuo zio?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",6], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g063_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo zio Luciano legge quasi esclusivamente romanzi.<br> Un tuo amico &egrave; invitato insieme a te alla festa di compleanno di zio Luciano.<br> Ti chiede di accompagnarlo in centro per comprare un regalo a Luciano.<br> Pensava di regalargli un romanzo che gli piace molto.<br> Tu sai che tuo zio detesta lo scrittore in questione.<br> Dici quindi che non ti sembra molto appropriato.<br> Il tuo amico ti domanda allora:<br /><strong>-Non regali i romanzi a tuo zio?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",7], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g071_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai organizzando una cena per alcuni amici.<br> Da bere hai due buoni vini: un bianco secco e un rosso invecchiato.<br> Il bianco vuoi servirlo fresco, ma per esaltare il profumo del rosso hai deciso di non metterlo in frigo.<br> Un tuo amico, poco esperto di vini, ti aiuta nei preparativi.<br> Guardando le due bottiglie, vuole assicurarsi di aver capito bene e ti chiede:<br /><strong>-IL ROSSO non metto in frigo?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",7], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g073_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai organizzando una cena per alcuni amici.<br> Da bere hai un buon vino rosso invecchiato.<br> Decidi che per esaltarne il profumo sar&agrave; meglio servirlo a temperatura ambiente.<br> Un tuo amico, poco esperto di vini, ti aiuta nei preparativi.<br> Vedendoti lasciare il vino rosso sul tavolo, ti chiede:<br /><strong>-Non metto il rosso in frigo?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",7], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g071_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai organizzando una cena per alcuni amici.<br> Da bere hai due buoni vini: un rosso leggero e un passito da meditazione.<br> Il rosso vuoi servirlo fresco, mentre il passito vuoi servirlo a temperatura ambiente.<br> Un tuo amico, poco esperto di vini, ti aiuta nei preparativi.<br> Guardando le due bottiglie, vuole assicurarsi di aver capito bene e ti chiede:<br /><strong>-IL ROSSO non metto in frigo?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",7], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g073_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai organizzando una cena per alcuni amici.<br> Da bere hai un vino rosso leggero.<br> Decidi di servirlo fresco, ma dimentichi di metterlo in frigo.<br> Un tuo amico, poco esperto di vini, ti aiuta nei preparativi.<br> Vedendo il vino rosso sul tavolo, ti chiede:<br /><strong>-Non metto il rosso in frigo?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",8], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g081_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in aeroporto.<br> I colleghi che si occupano del tabellone elettronico ti hanno spiegato che solo i voli internazionali vengono annunciati sul tabellone principale, mentre i voli locali sono annunciati solo su dei piccoli monitor.<br> I passeggeri sono al corrente del problema, ma alcuni non hanno le idee chiare in merito.<br> Un passeggero ti si avvicina e ti domanda:<br /><strong>-I VOLI LOCALI non annunciate sul tabellone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",8], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g083_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in aeroporto.<br> I colleghi che si occupano del tabellone elettronico ti hanno spiegato che i voli locali non vengono annunciati sul tabellone principale, ma solo su dei piccoli monitor in sala d&#39;aspetto.<br> Un passeggero fissa a lungo il tabellone e lo confronta con la sua carta d&#39;imbarco.<br> Dopo ti si avvicina e ti domanda:<br /><strong>-Non annunciate i voli locali sul tabellone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",8], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g081_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in aeroporto.<br> I colleghi che si occupano del tabellone elettronico ti hanno spiegato che solo i voli locali vengono annunciati sul tabellone, mentre i voli internazionali sono annunciati su dei monitor in sala d&#39;aspetto.<br> I passeggeri sono al corrente del problema, ma alcuni non hanno le idee chiare in merito.<br> Un passeggero ti si avvicina e ti domanda:<br /><strong>-I VOLI LOCALI non annunciate sul tabellone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",8], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g083_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in aeroporto.<br> Tutti i voli, locali e internazionali, vengono annunciati sul tabellone principale, che per&ograve; &egrave; un po&#39; confuso e difficile da leggere.<br> Un passeggero fissa a lungo il tabellone e lo confronta con la sua carta d&#39;imbarco.<br> Dopo ti si avvicina e ti domanda:<br /><strong>-Non annunciate i voli locali sul tabellone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",9], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g091_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un parassita infesta il tuo giardino.<br> Sono colpite molte piante, tra cui un cespuglio di rose e un&#39;aiuola di begonie.<br> Ti procuri un potente insetticida.<br> Il prodotto &egrave; un liquido che va spruzzato accuratamente sulle piante colpite.<br> Il venditore per&ograve; ti consiglia di non usarlo sulle begonie, perch&eacute; il prodotto &egrave; aggressivo e potrebbe danneggiare la pianta.<br> Un tuo amico si offre di applicare l&#39;insetticida, ma non ha ben capito la situazione.<br> Ti chiede allora:<br /><strong>-LE BEGONIE non spruzzo con l&#39;insetticida?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",9], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g093_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un parassita infesta il tuo giardino.<br> Ti procuri un potente insetticida.<br> Il prodotto &egrave; un liquido che va spruzzato accuratamente sulle piante colpite.<br> Il venditore per&ograve; ti consiglia di non usarlo sulle tue begonie, perch&eacute; il prodotto &egrave; aggressivo e potrebbe danneggiare la pianta.<br> Un tuo amico si offre di applicare l&#39;insetticida, ma dimentichi di avvertirlo del problema.<br> Mentre si appresta ad applicarlo sulle begonie, tu lo fermi bruscamente.<br> Lui ti chiede allora:<br /><strong>-Non spruzzo le begonie con l&#39;insetticida?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",9], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g091_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un parassita infesta il tuo giardino.<br> Sono colpite molte piante, tra cui un cespuglio di rose e un&#39;aiuola di begonie.<br> Ti procuri un potente insetticida.<br> Il prodotto &egrave; un liquido che va spruzzato accuratamente sulle piante colpite.<br> Il venditore per&ograve; ti consiglia di non usarlo sulle rose, perch&eacute; il prodotto &egrave; aggressivo e potrebbe danneggiare la pianta.<br> Un tuo amico si offre di applicare l&#39;insetticida, ma non ha ben capito la situazione.<br> Ti chiede allora:<br /><strong>-LE BEGONIE non spruzzo con l&#39;insetticida?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",9], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g093_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un parassita infesta il tuo giardino.<br> Ti procuri un potente insetticida.<br> Il prodotto &egrave; un liquido che va spruzzato accuratamente sulle piante colpite.<br> Si tratta di un prodotto ben tollerato dalle piante, quindi decidi di usarlo anche sulle tue amate begonie.<br> Un tuo amico si offre di applicare l&#39;insetticida.<br> Mentre si appresta ad applicarlo sulle begonie, tu noti che ha un grosso calabrone sulla spalla.<br> &#39;Stai fermo!&#39;, gli dici, e allontani il calabrone col tuo guanto.<br> Lui, che ha frainteso la situazione, ti chiede:<br /><strong>-Non spruzzo le begonie con l&#39;insetticida?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",10], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g101_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in una gioielleria.<br> Tu e un tuo collega siete stati incaricati di allestire una vetrinetta con delle &nbsp;statuine di cristallo che raffigurano animali: un cane, un&#39;aquila, un cervo eccetera.<br> Le statuine sono tutte in una grande scatola, ben imballate.<br> Ti accordi con il tuo collega perch&eacute; ti porga le statuine una alla volta.<br> Il cervo, per&ograve;, &egrave; eccezionalmente fragile, quindi hai chiesto al tuo collega di non toglierlo dalla scatola: sarai tu a prenderlo, per ultimo.<br> Il tuo collega, piuttosto smemorato, non ricorda esattamente e ti chiede:<br /><strong>-IL CERVO non tolgo dalla scatola?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",10], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g103_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in una gioielleria.<br> Tu e un tuo collega siete stati incaricati di allestire una vetrinetta con delle &nbsp;statuine di cristallo che raffigurano animali, tra cui una particolarmente fine di un cervo.<br> Le statuine sono tutte in una grande scatola, ben imballate.<br> Ti accordi con il tuo collega perch&eacute; ti porga le statuine una alla volta.<br> Il cervo, per&ograve;, &egrave; eccezionalmente fragile: ti viene il dubbio che il tuo collega possa romperlo.<br> Quando vedi che si accinge a prenderlo, quindi, lo fermi di botto.<br> Il tuo collega, perplesso, ti chiede:<br /><strong>-Non tolgo il cervo dalla scatola?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",10], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g101_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in una gioielleria.<br> Tu e un tuo collega siete stati incaricati di allestire una vetrinetta con delle &nbsp;statuine di cristallo che raffigurano animali: un cane, un&#39;aquila, un cervo eccetera.<br> Le statuine sono tutte in una grande scatola, ben imballate.<br> Ti accordi con il tuo collega perch&eacute; ti porga le statuine una alla volta.<br> L&#39;aquila, per&ograve;, &egrave; eccezionalmente fragile, quindi hai chiesto al tuo collega di non toglierla dalla scatola: sarai tu a prenderla, per ultima.<br> Il tuo collega, piuttosto smemorato, non ricorda esattamente e ti chiede:<br /><strong>-IL CERVO non tolgo dalla scatola?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",10], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g103_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Lavori in una gioielleria.<br> Tu e un tuo collega siete stati incaricati di allestire una vetrinetta con delle &nbsp;statuine di cristallo che raffigurano animali, tra cui una particolarmente fine di un cervo.<br> Le statuine sono tutte in una grande scatola, ben imballate.<br> Ti accordi con il tuo collega perch&eacute; ti porga le statuine una alla volta.<br> &nbsp;Mentre vedi che si accinge a prendere il cervo, ti ricordi all&#39;improvviso che dopo il lavoro devi passare dal commercialista.<br> Il tuo collega nota la tua espressione contrariata e, perplesso, ti chiede:<br /><strong>-Non tolgo il cervo dalla scatola?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",11], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g111_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tu e il tuo amico Marcello vivete in un quartiere con un problema di furti d&#39;auto.<br> Avete un solo posto auto nel garage e potete parcheggiarci solo una delle vostre due auto: una Fiat Punto e una Porsche.<br> Decidete di tenere in garage la Porsche e lasciare in strada la Punto.<br> Questa mattina hai preso la Porsche per andare al lavoro.<br> Gi&agrave; che c&#39;eri, hai perso qualche minuto per mettere in garage la Punto.<br> La sera per&ograve; torni a casa tardi con la Porsche e trovi, per qualche ragione, il garage sbarrato.<br> Non hai quindi altra scelta che parcheggiare la Porsche in strada.<br> Marcello per&ograve; guarda dalla finestra e vede la Porsche al lato della strada.<br> Al tuo rientro, quindi, ti domanda:<br /><strong>-LA PORSCHE non hai parcheggiato in garage?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",11], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g113_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tu e il tuo amico Marcello vivete in un quartiere con un problema di furti d&#39;auto.<br> Avete un posto auto nel garage e avete sempre cura di parcheggiare la vostra auto, una Porsche, nel garage.<br> Questa mattina hai preso la Porsche per andare al lavoro.<br> La sera per&ograve; torni a casa tardi e trovi, per qualche ragione, il garage sbarrato.<br> Non hai quindi altra scelta che parcheggiare in strada.<br> Marcello per&ograve; guarda dalla finestra e vede la Porsche al lato della strada.<br> Al tuo ritorno, quindi, ti domanda:<br /><strong>-Non hai parcheggiato la Porsche in garage?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",11], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g111_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tu e il tuo amico Marcello vivete in un quartiere con un problema di furti d&#39;auto.<br> Avete un solo posto auto nel garage e potete parcheggiarci solo una delle vostre due auto: una Fiat Punto e una Porsche.<br> Decidete di tenere in garage la Porsche e lasciare in strada la Punto.<br> Questa mattina hai preso la Porsche per andare al lavoro.<br> La sera torni a casa e la rimetti in garage.<br> Marcello per&ograve; guarda dalla finestra e vede una Porsche simile alla vostra al lato della strada.<br> Al tuo rientro, quindi, ti domanda:<br /><strong>-LA PORSCHE non hai parcheggiato in garage?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",11], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g113_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tu e il tuo amico Marcello vivete in un quartiere con un problema di furti d&#39;auto.<br> Avete un posto auto nel garage e avete sempre cura di parcheggiare la vostra auto, una Porsche, in garage.<br> Questa mattina hai preso la Porsche per andare al lavoro.<br> La sera torni a casa e la rimetti in garage.<br> Marcello per&ograve; guarda dalla finestra e vede una Porsche simile alla vostra al lato della strada.<br> Al tuo ritorno, quindi, ti domanda:<br /><strong>-Non hai parcheggiato la Porsche in garage?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",12], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g121_5.mp3' type='audio/mpeg'></source></audio> <br><br><br>La tua amica Matilde ti ha prestato un gran numero di libri e fumetti.<br> Un giorno ti dice che vorrebbe passare a casa tua nel pomeriggio a riprenderli, ma tu sarai fuori casa.<br> Chiedi allora al tuo coinquilino il favore di mettere tutto in uno scatolone e darlo a Matilde.<br> Gli chiedi per&ograve; di non mettere nella scatola &#39;Moby Dick&#39;: anche quello te lo ha dato Matilde, ma era un regalo per il tuo compleanno.<br> Prima che tu esca, il tuo coinquilino vuole essere sicuro di aver capito bene.<br> Ti chiede:<br /><strong>-&#39;MOBY DICK&#39; non restituisci a Matilde?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",12], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g123_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un giorno la tua amica Matilde ti dice che vorrebbe passare a casa tua nel pomeriggio a riprendere alcune cose che ti aveva prestato, ma tu sarai fuori casa.<br> Prepari allora uno scatolone con gli oggetti in questione e chiedi al tuo coinquilino il favore di darlo a Matilde.<br> Tempo prima Matilde ti aveva regalato una bella copia illustrata di &#39;Moby Dick&#39;.<br>Il tuo coinquilino si ricorda di questo fatto, ma ricorda vagamente che si trattasse di un prestito.<br> Gettando un occhio al contenuto dello scatolone &egrave; sorpreso di non vedere il libro.<br> Ti chiede allora:<br /><strong>-Non restituisci &#39;Moby Dick&#39; a Matilde?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",12], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g121_5.mp3' type='audio/mpeg'></source></audio> <br><br><br>La tua amica Matilde ti ha prestato un gran numero di libri e fumetti.<br> Un giorno ti dice che vorrebbe passare a casa tua nel pomeriggio a riprenderli, ma tu sarai fuori casa.<br> Chiedi allora al tuo coinquilino il favore di mettere tutto in uno scatolone e darlo a Matilde.<br> Gli chiedi per&ograve; di non mettere nella scatola &#39;Delitto e castigo&#39;: anche quello te lo ha dato Matilde, ma era un regalo per il tuo compleanno.<br> Prima che tu esca, il tuo coinquilino vuole essere sicuro di aver capito bene.<br> Ti chiede:<br /><strong>-&#39;MOBY DICK&#39; non restituisci a Matilde?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",12], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g123_3.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un giorno la tua amica Matilde ti dice che vorrebbe passare a casa tua nel pomeriggio a riprendere alcune cose che ti aveva prestato, ma tu sarai fuori casa.<br> Prepari allora uno scatolone con gli oggetti in questione e chiedi al tuo coinquilino il favore di darlo a Matilde.<br> Tempo prima Matilde ti aveva prestato anche una bella copia illustrata di &#39;Moby Dick&#39;.<br>Il tuo coinquilino si ricorda di questo fatto.<br> Gettando un occhio al contenuto dello scatolone &egrave; sorpreso di non vedere il libro, che hai sbadatamente dimenticato sullo scaffale.<br> Ti chiede allora:<br /><strong>-Non restituisci &#39;Moby Dick&#39; a Matilde?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",13], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g131_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Nella tua citt&agrave; &egrave; cambiata la raccolta dei rifiuti.<br> La raccolta differenziata verr&agrave; ora fatta porta a porta da un furgoncino.<br> Gli operatori raccoglieranno vetro e plastica.<br> Non sono per&ograve; attrezzati per la carta, che dovr&agrave; ancora essere depositata negli appositi bidoni in strada.<br> Il tuo coinquilino si incarica di fare la prima consegna l&#39;indomani.<br> Non &egrave; per&ograve; sicuro di aver capito la situazione e ti chiede:<br /><strong>-LA CARTA non consegno al furgoncino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",13], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g133_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Nella tua citt&agrave; &egrave; cambiata la raccolta dei rifiuti.<br> La raccolta della carta verr&agrave; ora fatta porta a porta da un furgoncino.<br> Stamattina per&ograve; hai trovato nella cassetta della posta una comunicazione che spiegava che gli operatori non sono ancora attrezzati e il servizio di raccolta della carta sarebbe cominciato solo la settimana successiva.<br> Il tuo coinquilino si era incaricato di fare la prima consegna l&#39;indomani.<br> Quando gli metti in mano la comunicazione dell&#39;azienda dei rifiuti, lui ti chiede perplesso:<br /><strong>-Non consegno la carta al furgoncino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",13], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g131_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Nella tua citt&agrave; &egrave; cambiata la raccolta dei rifiuti.<br> La raccolta differenziata verr&agrave; ora fatta porta a porta da un furgoncino.<br> Gli operatori raccoglieranno vetro e carta.<br> Non sono per&ograve; attrezzati per la plastica, che dovr&agrave; ancora essere depositata negli appositi bidoni in strada.<br> Il tuo coinquilino si incarica di fare la prima consegna l&#39;indomani.<br> Non &egrave; per&ograve; sicuro di aver capito la situazione e ti chiede:<br /><strong>-LA CARTA non consegno al furgoncino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",13], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g133_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Nella tua citt&agrave; &egrave; cambiata la raccolta dei rifiuti.<br> La raccolta della carta verr&agrave; ora fatta porta a porta da un furgoncino.<br> Il tuo coinquilino si incarica di fare la prima consegna domani.<br> Stamattina hai trovato nella cassetta della posta una comunicazione dell&#39;azienda dei rifiuti, che riguardava per&ograve; un altro cambiamento nella raccolta del vetro.<br> Quando metti in mano la comunicazione al tuo coinquilino, lui, confuso, ti chiede:<br /><strong>-Non consegno la carta al furgoncino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",14], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g141_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Vivi in appartamento ma ti piace coltivare piante aromatiche.<br> In casa hai vasi di rosmarino, origano, basilico e altre piante.<br> Nelle belle giornate metti tutti i vasi sul balcone a prendere sole.<br> Le temperature per&ograve; si sono fatte rigide e hai deciso di tenere in casa il basilico, per paura che il freddo lo danneggi.<br> Un amico, che passa a trovarti di tanto in tanto, oggi ti d&agrave; una mano a mettere fuori i vasi.<br> Non essendo sicuro di aver capito, ti domanda:<br /><strong>-IL BASILICO non sposti sul balcone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",14], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g143_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Vivi in appartamento ma ti piace coltivare piante aromatiche.<br> Nelle belle giornate metti tutti i vasi sul balcone a prendere sole.<br> Le temperature per&ograve; si sono fatte rigide e hai deciso di tenere in casa il basilico, per paura che il freddo lo danneggi.<br> Un amico, che non conosce le tue nuove abitudini, &egrave; venuto a trovarti.<br> Ti d&agrave; una mano a mettere fuori i vasi.<br> Quando lo vedi spostare in balcone il basilico, tu lo fermi garbatamente e riporti la pianta in casa.<br> Perplesso, il tuo amico ti chiede:<br /><strong>-Non sposti il basilico sul balcone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",14], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g141_2.mp3' type='audio/mpeg'></source></audio> <br><br><br>Vivi in appartamento ma ti piace coltivare piante aromatiche.<br> In casa hai vasi di rosmarino, origano, basilico e altre piante.<br> Nelle belle giornate metti tutti i vasi sul balcone a prendere sole.<br> Le temperature per&ograve; si sono fatte rigide e hai deciso di tenere in casa l&#39;origano, per paura che il freddo lo danneggi.<br> Un amico, che passa a trovarti di tanto in tanto, oggi ti d&agrave; una mano a mettere fuori i vasi.<br> Non essendo sicuro di aver capito, ti domanda:<br /><strong>-IL BASILICO non sposti sul balcone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",14], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g143_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Vivi in appartamento ma ti piace coltivare piante aromatiche.<br> Nelle belle giornate metti tutti i vasi sul balcone a prendere sole.<br> Nelle scorse settimane, le temperature si erano fatte rigide e avevi deciso di tenere in casa il basilico, per paura che il freddo lo danneggiasse.<br> Oggi per&ograve; &egrave; una bella giornata tiepida, quindi pensi di mettere in balcone anche il basilico.<br> Un amico &egrave; venuto a trovarti e ti d&agrave; una mano a mettere fuori i vasi.<br> L&#39;occhio del tuo amico cade su un vecchio appunto che avevi lasciato in cucina settimane fa.<br> L&#39;appunto recita &#39;Non spostare il basilico!&#39;. Perplesso, il tuo amico ti chiede:<br /><strong>-Non sposti il basilico sul balcone?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",15], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g151_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai mettendo a nuovo il tuo salotto e hai deciso per un look minimalista.<br> Inizialmente pensavi di dipingere tutto di bianco.<br> All&#39;ultimo momento, decidi che sarebbe bello, in seguito, dipingere la porta di un rosa pallido.<br> Vuoi quindi dare il bianco a tutto il resto, avendo cura di lasciare la porta al naturale.<br> Il tuo amico Carlo ha insistito per svolgere il lavoro, ma non &egrave; sicuro di aver capito i tuoi piani.<br> Ti domanda quindi:<br /><strong>-LA PORTA non dipingo di bianco?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",15], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g153_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai mettendo a nuovo il tuo salotto e hai deciso per un look minimalista.<br> Inizialmente pensavi di dipingere tutto di bianco.<br> All&#39;ultimo momento, decidi che sarebbe bello lasciare la porta al naturale.<br> Il tuo amico Carlo ha insistito per svolgere il lavoro, ma non &egrave; al corrente del tuo ripensamento.<br> Ti ricordi del problema solo quando Carlo si accinge a dipingere la porta.<br> Lo fermi bruscamente.<br> Lui quindi ti domanda:<br /><strong>-Non dipingo la porta di bianco?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",15], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g151_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai mettendo a nuovo il tuo salotto e hai deciso per un look minimalista.<br> Inizialmente pensavi di dipingere tutto di bianco.<br> All&#39;ultimo momento, decidi che sarebbe bello, in seguito, dipingere la finestra di un rosa pallido.<br> Vuoi quindi dare il bianco a tutto il resto, avendo cura di lasciare la finestra al naturale.<br> Il tuo amico Carlo ha insistito per svolgere il lavoro, ma non &egrave; sicuro di aver capito i tuoi piani.<br> Ti domanda quindi:<br /><strong>-LA PORTA non dipingo di bianco?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",15], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g153_1.mp3' type='audio/mpeg'></source></audio> <br><br><br>Stai mettendo a nuovo il tuo salotto e hai deciso per un look minimalista.<br> Pensavi di dipingere tutto di bianco, porta inclusa.<br> Il tuo amico Carlo ha insistito per svolgere il lavoro.<br> Carlo d&agrave; una prima mano di bianco alle pareti, ma cos&igrave; facendo finisce il barattolo della vernice.<br> Tu allora scendi in cantina per prendere altra vernice.<br> La cantina per&ograve; &egrave; poco illuminata e per errore prendi un barattolo di vernice rosa anzich&eacute; bianca.<br> Poco dopo, Carlo vede il barattolo e ti domanda:<br /><strong>-Non dipingo la porta di bianco?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",16], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g161_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Ti &egrave; stata regalata una grossa quantit&agrave; di funghi assortiti: porcini, ovoli, chiodini e altri.<br> Si pone il problema di come conservarli.<br> Decidi di essiccarli e metterli sottovuoto, con l&#39;eccezione dei porcini, che preferisci mangiare ancora freschi.<br> Il tuo amico Luca vuole aiutarti a preparare il tutto.<br> L&igrave; per l&igrave;, per&ograve;, vedendo tanti tipi diversi di funghi, vuole essere sicuro di aver capito bene.<br> Ti chiede allora:<br /><strong>-I PORCINI non metti sotto vuoto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",16], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/ynta_g163_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Ti &egrave; stata regalata una grossa quantit&agrave; di funghi assortiti.<br> Si pone il problema di come conservarli.<br> Ne parli con il tuo amico Luca.<br> Decidi di essiccare i funghi e metterli sottovuoto.<br> &nbsp;Luca ti aiuter&agrave; a preparare il tutto.<br> All&#39;ultimo momento, per&ograve;, decidi che i porcini sarebbe meglio mangiarli freschi.<br> Li cuoci subito per condirci le tagliatelle per la cena.<br> Luca, che non &egrave; al corrente del tuo ripensamento, ti vede cucinare e ti chiede:<br /><strong>-Non metti i porcini sotto vuoto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",16], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g161_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Ti &egrave; stata regalata una grossa quantit&agrave; di funghi assortiti: porcini, ovoli, chiodini e altri.<br> Si pone il problema di come conservarli.<br> Decidi di essiccarli e metterli sottovuoto, con l&#39;eccezione degli ovoli, che preferisci mangiare ancora freschi.<br> Il tuo amico Luca vuole aiutarti a preparare il tutto.<br> L&igrave; per l&igrave;, per&ograve;, vedendo tanti tipi diversi di funghi, vuole essere sicuro di aver capito bene.<br> Ti chiede allora:<br /><strong>-I PORCINI non metti sotto vuoto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["e",16], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/yntb_g163_4.mp3' type='audio/mpeg'></source></audio> <br><br><br>Ti &egrave; stata regalata una grossa quantit&agrave; di funghi assortiti.<br> Si pone il problema di come conservarli.<br> Ne parli con il tuo amico Luca.<br> Decidi di essiccare i funghi e metterli sottovuoto.<br> &nbsp;Luca ti aiuter&agrave; a preparare il tutto.<br> Mettete sotto vuoto gran parte dei funghi, ma sbadatamente dimentichi i porcini sul tavolo della cucina.<br> Tua sorella, che ha frainteso le tue intenzioni, si appresta a cucinare i porcini per la cena.<br> Luca vede la scena e ti chiede:<br /><strong>-Non metti i porcini sotto vuoto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",17], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F01.mp3' type='audio/mpeg'></source></audio> <br><br><br>Da qualche giorno, il vostro cane ha la febbre e il vostro gatto ha mal di stomaco. <br>Tu e il tuo coinquilino concordate di portare entrambi dal veterinario quanto prima: non &egrave; per&ograve; possibile portarli insieme.<br>Questo pomeriggio decidi di portare dal veterinario il cane.<br>La sera il tuo coinquilino non &egrave; sicuro di aver capito bene, e ti chiede:<br /><strong>-IL CANE hai portato dal veterinario?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",18], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F02.mp3' type='audio/mpeg'></source></audio> <br><br><br>Per alcuni amici hai preparato una ricca cena con molte portate, e hai comprato un buon dolce in pasticceria.<br> Un tuo amico, strabiliato, ti chiede se hai avuto aiuto nella preparazione. Dici che hai preparato tutte le portate con le tue mani, con l&#39;eccezione di una, che hai comprato in un negozio gi&agrave; pronta: inviti anzi il tuo amico a indovinare quale.<br /><strong>-IL DOLCE hai comprato in negozio?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",19], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F03.mp3' type='audio/mpeg'></source></audio> <br><br><br>Vuoi preparare del sushi, ma &egrave; la prima volta e hai qualche dubbio.<br>In pescheria compri orata e sgombro.<br>Per non rischiare di rovinare la cena, decidi di fare il sushi solo con l&#39;orata, e di cucinare lo sgombro alla griglia. <br> Giorni dopo incontri il pescivendolo, che &egrave; curioso di sapere com&#39;&egrave; andata. Ti chiede: &nbsp; &nbsp;<br /><strong>-L&#39;ORATA avete mangiato cruda?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",20], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F04.mp3' type='audio/mpeg'></source></audio> <br><br><br>In questi giorni fa molto freddo.<br>Sei in cerca di qualcosa da bruciare nel camino.<br>Trovi della legna secca e della carbonella, che per&ograve; tuo fratello ti aveva raccomandato di usare solo per il barbecue. Decidi quindi di bruciare la legna.<br>Tuo fratello, al suo rientro, ti chiede:&nbsp;<br /><strong>-LA LEGNA hai bruciato nel camino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",26], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F10.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tutte le mattine compri il tuo quotidiano dal tuo edicolante di fiducia.<br>Di tanto in tanto gli chiedi anche di tenerti da parte il tuo settimanale preferito.<br>Domattina per&ograve; non farai in tempo a passare in edicola.<br>Oggi quindi chiedi all&#39;edicolante il favore di tenerti da parte il quotidiano di domani. Non essendo sicuro di aver capito bene, lui ti domanda:<br><strong>-IL SETTIMANALE le tengo da parte?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",27], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F11.mp3' type='audio/mpeg'></source></audio> <br><br><br>Oggi fai da babysitter a un bambino figlio di amici.<br>Decidi di portarlo ai giardinetti.<br>Il bambino ha con s&eacute; due giocattoli, un robot e un dinosauro, il suo preferito. Di ritorno a casa, il bambino si accorge di non avere pi&ugrave; il robot, e scoppia in lacrime. Il padre del piccolo non &egrave; sicuro di aver capito bene.<br>Ti chiede:<br><strong>-IL DINOSAURO ha perso ai giardinetti?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",28], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F12.mp3' type='audio/mpeg'></source></audio> <br><br><br>Il tuo amico Ermanno ha scommesso che se la sua squadra del cuore avesse vinto il campionato, si sarebbe tinto i capelli di azzurro.<br>Dopo la vittoria, per&ograve;, Ermanno decide di tingersi di azzurro la barba cos&igrave;, dopo, potr&agrave; tagliarsela senza troppi problemi.<br>Incontri un amico comune che non &egrave; sicuro di aver capito com&#39;&egrave; andata,<br>e ti chiede:<br /><strong>-I CAPELLI si &egrave; tinto di azzurro?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",30], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F14.mp3' type='audio/mpeg'></source></audio> <br><br><br>A casa siete in grossi guai: l&#39;altro giorno si &egrave; rotta la lavatrice, oggi si &egrave; rotto il frigorifero.<br>Le vostre finanze mensili non vi permettono di pagare la riparazione di entrambi.<br>Inizialmente eravate d&#39;accordo per riparare la lavatrice, ma ora ti sembra pi&ugrave; urgente riparare il frigo. Il tuo coinquilino ti domanda:<br /><strong>-LA LAVATRICE portiamo a riparare?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",37], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F21.mp3' type='audio/mpeg'></source></audio> <br><br><br>A casa vostra c&#39;&egrave; un armadietto in cui tenete i medicinali, pi&ugrave; altri dispositivi medici come il termometro e i cerotti.<br>Dentro c&#39;&egrave; una certa confusione. Il tuo coinquilino apre l&#39;armadietto e non riesce a trovare il termometro, che &egrave; nascosto dalle scatole dei farmaci.<br>Ti chiede allora:<br /><strong>-Hai tolto il termometro dall&#39;armadietto?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",38], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F22.mp3' type='audio/mpeg'></source></audio> <br><br><br>Un contadino vostro amico vi rifornisce di frutta e verdura di stagione.<br>Ieri vi ha recapitato due ceste di limoni.<br>Eravate rimasti d&#39;accordo per incontrare il contadino oggi pomeriggio per regolare il conto. Tu per&ograve; hai avuto un contrattempo e non hai potuto farlo.<br>Il tuo coinquilino ti vede e ti chiede:&nbsp;<br /><strong>-Hai pagato i limoni al contadino?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",39], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F23.mp3' type='audio/mpeg'></source></audio> <br><br><br>Hai qualche nozione di idraulica.<br>Quando un giorno vi si allaga il bagno, tu e il tuo coinquilino decidete di provare a riparare l&#39;impianto da soli.<br>Rimuovete i sanitari e cercate di capire cosa si sia rotto.<br>Tu fai del tuo meglio, ma ti sembra che tutto sia in ordine.<br>Il tuo coinquilino, confuso, ti chiede:<br><strong>-Hai trovato il pezzo da sostituire?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",40], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F24.mp3' type='audio/mpeg'></source></audio> <br><br><br>Dal soffitto di casa vostra entra acqua quando piove.<br>Ti incarichi di telefonare al padrone di casa, ma chiedi al tuo coinquilino di essere presente.<br>Alzata la cornetta, cerchi di ricordare il numero di telefono ma ti accorgi di averlo dimenticato.<br>In quel momento, il tuo coinquilino ti guarda e ti chiede:<br><strong>-Sai il numero a memoria?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",41], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F25.mp3' type='audio/mpeg'></source></audio> <br><br><br>Ieri hai avuto da fare in giardino.<br>Hai avuto bisogno che i vicini ti prestassero una pala.<br>Stamattina, per prima cosa, hai avuto cura di restituirla.<br>Ora il tuo coinquilino, tornato a casa, vuole essere sicuro che la pala sia tornata ai suoi legittimi proprietari.<br>Ti chiede:<br><strong>-Hai restituito la pala ai vicini?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",43], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F27.mp3' type='audio/mpeg'></source></audio> <br><br><br>Di recente nella tua citt&agrave; sono stati avvistati stormi di pappagalli verdi.<br>Nel tuo quartiere, per&ograve; non si sono ancora visti.<br>Un giorno ti affacci dalla finestra della tua camera da letto e vedi una decina di pappagalli sull&#39;albero pi&ugrave; vicino.<br>Poco dopo incontri il tuo coinquilino che, divertito, ti domanda:<br><strong>-Hai visto i pappagalli sull&#39;albero?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",44], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F28.mp3' type='audio/mpeg'></source></audio> <br><br><br>Nel tuo quartiere si organizza una grande tombola di Natale.<br>Lo scorso Natale hai vinto il primo premio e hai avuto il dubbio onore di portarti a casa un enorme elefante di pezza.<br>Oggi un amico viene a farti visita e, vedendo l&#39;elefante in salotto, ti domanda:<br /><strong>-Hai vinto il primo premio alla tombola di Natale?<br></strong></div>", as: ["S&igrave;", "No"]}],
    [["iller",48], "Question",       {q: "<div style=\"width: 40em;\"><audio autoplay controls><source src='http://surveygizmolibrary.s3.amazonaws.com/library/196445/F32.mp3' type='audio/mpeg'></source></audio> <br><br><br>Tuo fratello &egrave; raffreddato.<br>Sapendo di fargli piacere, gli prepari una tazza di t&egrave; caldo.<br>Sai per&ograve; che il t&egrave; gli piace non troppo forte, quindi lasci la bustina in infusione per tre minuti esatti, e la togli.<br>Tuo fratello, che ti sente armeggiare in cucina gi&agrave; da parecchi minuti, ti chiede:<br><strong>-Hai tolto la bustina dalla tazza?<br></strong></div>", as: ["S&igrave;", "No"]}],
    //
    // 10 self-paced-reading filler sentences.

];
